### ISSUE TITLE
Can't find v115 release

### ISSUE THREAD

**Issue by spa5k** [Alex313031/Thorium-MacOS#1]
Can't find v115 release

**Comment by Alex313031** [comment]
@gz83 @spa5k Well, he is not really rushing. It was supposed to be out right now. But Midzer (the contributor who builds the MacOS releases since I don't have a Mac) is on vacation, and he doesn't have access to the build machine right now. On Sunday he will be back, so expect the releases Sunday or Monday.

**Comment by csrutil** [comment]
Thank you @Alex313031 for the updates, I also wondering why we don't a new release, lol! and BTW, do we have tutorial for building the macOS build? Thank you again!

**Comment by Alex313031** [comment]
@csrutil @spa5k I think @midzer has died (not literally) lol. Until I can get ahold of him, I can't release M115 MacOS.
Sorry.

**Comment by spa5k** [comment]
Lol you scared me 😂

**Comment by midzer** [comment]
I'm alive. We still have to fix current build issues. Message me on IRC, @Alex313031

**Comment by csrutil** [comment]
haha, you guys buy me the whole day laugh! have a great day! @midzer @Alex313031

**Comment by Alex313031** [comment]
@midzer You should be able to build Thorium if you disable the HLS args gn flag like you had to do with your experimental Chromium builds.

**Comment by Alex313031** [comment]
@csrutil @spa5k Here ya'll go > https://github.com/Alex313031/Thorium-MacOS/releases/tag/M115.0.5790.172

@midzer Has risen from the dead!

**Comment by midzer** [comment]
One problem solved, two more ahead ;D

**Comment by Alex313031** [comment]
@midzer What's the two more?

**Comment by midzer** [comment]
Solving world peace and the unity of mankind.

**Comment by csrutil** [comment]
Thank you guys, I just made a donation, hope you guys have a good day!

<img width="557" alt="Screen Shot 2023-09-20 at 8 45 24 AM" src="https://github.com/Alex313031/Thorium-MacOS/assets/6078291/579c9002-215d-428b-b81d-85b87db22482">

**Comment by Alex313031** [comment]
@csrutil Aw thank you sir.
