### ISSUE TITLE
Udemy videos don't show up

### ISSUE THREAD

**Issue by art-stankov** [Alex313031/Thorium-MacOS#11]
**System Details**
MacOS Sonoma 14.0
Thorium Version 116.0.5845.169 (Official Build) (arm64)

**Problem**
There is a gray square in place of a video on Udemy and play/pause button doesn't seem to do anything.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-MacOS/assets/139538265/4a999319-4696-41a8-83f1-bbae88ddef69)

**Comment by gz83** [comment]
Is this page working on chrome?

@art-stankov

**Comment by Ok9xNirab** [comment]
@gz83 Same issue from me!

![Screenshot 2023-10-18 at 9 42 21 AM](https://github.com/Alex313031/Thorium-MacOS/assets/40653908/c6fffe3b-4f22-4d48-a671-2699f3516670)

> Is this page working on chrome?

Yes. I'm using brave browser.

**Comment by gz83** [comment]
> @gz83 Same issue from me!
> 
> ![Screenshot 2023-10-18 at 9 42 21 AM](https://user-images.githubusercontent.com/40653908/276077462-c6fffe3b-4f22-4d48-a671-2699f3516670.png)
> 
> > Is this page working on chrome?
> 
> Yes. I'm using brave browser.

Does this page use widevine?

@Ok9xNirab

**Comment by Ok9xNirab** [comment]
@gz83  Yes. **Google DRM (Widevine)**

**Comment by gz83** [comment]
What I mean is whether this webpage uses Widevine to process audio and video.  If so, then I'm sorry, it may be because of Widevine's VMP verification. Currently, Thorium cannot perform VMP verification, so it cannot play audio and video that require VMP verification.  To conduct VMP verification, we need to pay a large fee to Widevine, which we are temporarily unable to pay.

@Ok9xNirab

**Comment by Ok9xNirab** [comment]
Thank you @gz83 for describing this issue.

**Comment by art-stankov** [comment]
@gz83 As I see on the Internet, the Widevine is indeed used as DRM on Udemy

**Comment by gz83** [comment]
> @gz83 As I see on the Internet, the Widevine is indeed used as DRM on Udemy

Please see my previous reply

@art-stankov

**Comment by gz83** [comment]
According to Alex, a fee of US$5,000 needs to be paid to Widevine, but whether this number is calculated on a monthly or annual basis I am not clear yet.

@jcraig999

**Comment by jcraig999** [comment]
Based upon my own research, I can surmise that it is probably annual because there are services out there where you can get a license for around $99 a month. I wouldn't be able to pay the $5000 out right, but if Alex set up some kind of pool where people can donate (I know you can do this on PayPal), I would definitely donate on a monthly or bimonthly basis.
@gz83

**Comment by jigglywatts** [comment]
I could do $10/month

**Comment by jcraig999** [comment]
I have a friend that already has a Widevine key, and he said that you all can implement it into the project. Do you have discord or telegram so he can reach out or should he contact Alex via email?
@gz83

**Comment by gz83** [comment]
Thank you very much for your and your friends' help. If this key is valid, it will solve many problems related to widevine.

Please contact Alex via email and CC me on the email, thank you.

@jcraig999

**Comment by jcraig999** [comment]
What is your email? I don't see it in your profile. 
@gz83

**Comment by gz83** [comment]
I have temporarily made my email address public, can you see my email address?  My email address may appear in my profile or in your email.

@jcraig999

**Comment by jcraig999** [comment]
Got it. You can make it private again. He will reach out as soon as possible. Feel free to ping me if you don't hear anything.
@gz83

**Comment by gz83** [comment]
Has your friend emailed us? I haven't received an email from your friend yet.

@jcraig999

**Comment by jcraig999** [comment]
Probably not yet. I will follow up.

**Comment by jcraig999** [comment]
Sorry it took me so long to reply. He said that, unfortunately, he can't give you all the key without losing access to it himself.
@gz83

**Comment by gz83** [comment]
It doesn't matter

@jcraig999

**Comment by jcraig999** [comment]
Sorry for the late reply. What doesn't matter?
@gz83

**Comment by gz83** [comment]
> Sorry for the late reply. What doesn't matter? @gz83

What I mean is: we don't feel any dissatisfaction or frustration that your friend was unable to provide a key for widevine, and we still appreciate the time and effort you and your friend put into solving the widevine problem, despite ultimately failing to share the key for widevine with us.

@jcraig999

**Comment by Alex313031** [comment]
@gz83 @jcraig999 Yeah, what gz83 said lol.
