### ISSUE TITLE
Missing Vertical Tab Feature in Thorium Browser

### ISSUE THREAD

**Issue by Sohampatra1** [Alex313031/Thorium-MacOS#17]
I am currently using the Thorium browser and have noticed that it lacks the vertical tab feature. This absence is causing inconvenience and frustration while managing multiple tabs.

I would like to request the addition of a vertical tab feature in the Thorium browser. This feature would allow users to view and manage their open tabs in a vertical layout, making it easier to navigate and switch between them. It would be ideal if the vertical tab feature could be implemented similar to other popular browsers such as Google Chrome or Mozilla Firefox.

*

**Comment by gz83** [comment]
There are similar issues in other repos and are marked as duplicates.
