### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by intellitour** [Alex313031/Thorium-MacOS#18]
Browser is advised as:

<img width="634" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/5827270/d7f9a27a-604f-4a04-9ed3-b86de1aba6c2">

But...

This is Thorium running on my MacBook Pro 16" (M1 Max - 64gb RAM):

<img width="1840" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/5827270/0aad51ce-c4eb-45fc-8913-c21066ebc3af">

And this is the same benchmark on Safari:

<img width="1840" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/5827270/6cae7f22-6b53-46c2-9d8c-2fea28efd397">

And this os the same benchmark on Google Chrome:

<img width="1840" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/5827270/edf809bd-3f3b-4cf0-892e-6a6b29fe2ad6">

So... Thorium is the slowest. I don't get it. Am I doing something wrong?

**Comment by jigglywatts** [comment]
Here is Thorium benchmark on a M2 Max with 32GB ram and a bunch of other tabs and apps open

![CleanShot 2023-10-19 at 13 13 21@2x](https://github.com/Alex313031/Thorium-MacOS/assets/135018323/0b7b1928-0a34-41f9-8db1-9d45df4021dd)

**Comment by Alex313031** [comment]
@intellitour No, that is strange though. But then again I don't have a Mac, and rely on another person to actually build it and test it.

It should at the very least not be *slower* than Chrome. However, Safari will outperform it, since it is highly tuned for apple hardware, and is built on a different web engine (webkit versus chromium's blink), so it shouldn't be used for competing Chromium based browser performance. Safari seems to beat any other browser. That's one side effect of being apple being a walled garden that makes both hardware and software.

We still need to build M117 for MacOS, so you can test it again when we make new release. Also make sure that you are comparing the same major version number (so 117), as it is not an apples to apples comparison otherwise, and performance may be better or worse depending on version.

@midzer We should test this for M117.

**Comment by intellitour** [comment]
I actually tested it against latest Chrome version (118.0.5993.88).

**Comment by midzer** [comment]
We're in the process of building M117 for Mac.

**Comment by csrutil** [comment]
Chip:	Apple M1 Pro
Total Number of Cores:	10 (8 performance and 2 efficiency)
Memory:	32 GB
Safari Version 16.6.1 (17615.3.12.11.5, 17615)

<img width="957" alt="Screen Shot 2023-10-22 at 7 09 42 PM" src="https://github.com/Alex313031/Thorium-MacOS/assets/6078291/095ef6d0-d535-4003-8d05-eb7e29849561">

**Comment by peter-lxc** [comment]
Chip: Apple M2 Pro
Total Number of Cores: 10 (6 performance and 4 efficiency)
Memory: 16 GB
OS - Sonoma 14.0
Thorium - Version 116.0.5845.169 (Official Build) (arm64)

<img width="1054" alt="Screenshot 2023-10-22 at 13 47 15" src="https://github.com/Alex313031/Thorium-MacOS/assets/78224555/2f4cdea2-3e09-43fc-8fea-fd5a55011e41">

and same hardware Safari 17.0 (19616.1.27.211.1)

<img width="987" alt="Screenshot 2023-10-22 at 13 51 38" src="https://github.com/Alex313031/Thorium-MacOS/assets/78224555/18e51750-326a-4eb9-b779-8b9ff5e7fb64">

**Comment by viktorvsk** [comment]
Mac M1 2020, 16GB, Sonoma 14.0

| Browser | Speedometer |
| ---- | ---- |
| Chrome Version 114.0.5735.133 (Official Build) (arm64)  | 387 |
| Thorium Version 116.0.5845.169 (Official Build) (arm64) | 383 |
| Safari Version 17.0 (19616.1.27.211.1) | 424 |

Even though Thorium and Chromium are very close — at least animations are WAY MUCH better in Chromium

**Comment by midzer** [comment]
Mac M1 2020 (Heatpad modded), 16GB, Sonoma 14.1, idle system with (probably) minimal background tasks

Chromium M117: 433 (+-4,9)
Safari latest: ~435

Still trying to get Thorium build for M117. Linker errors...scores will follow once successfully built.

**Comment by thataboy** [comment]
WOW!

M1 base processor 16GB RAM, Sonoma 14.2

thorium 119.0.6045.214: 397
chrome 120.0.6099.216: 347 
safari: 449

Kudos to the devs. 

Note: I have quite a few extensions in thorium and none in safari since I don't use safari

**Comment by piotrnikov** [comment]
Apple M3 Max
Thorium 120.0.6099.235
![Screenshot 2024-01-31 at 14 19 07](https://github.com/Alex313031/Thorium-MacOS/assets/28474540/6cd96cd2-cd03-4f96-8ead-4118453283df)
Safari 17.3 
![Screenshot 2024-01-31 at 14 18 16](https://github.com/Alex313031/Thorium-MacOS/assets/28474540/f763f977-cecc-4876-8d70-b2bebded6135)
Yikes.
That's some difference.
I don't use Safari but I just might!
Any plans on looking into this?
Best,

Piotr

**Comment by midzer** [comment]
@piotrnikov Strange, I had ~450 on a M1 Air.

@Alex313031 Do we (mis)optimize for a certain ARM64 Mac architecture?

**Comment by piotrnikov** [comment]
@midzer I don't know if it's useful or not but I have these Extensions installed on Thorium...
![Screenshot 2024-01-31 at 14 55 32](https://github.com/Alex313031/Thorium-MacOS/assets/28474540/e08f3804-3fe0-49a2-b675-5b51fffa6e3c)

**Comment by midzer** [comment]
In fact, Browser extensions *do* slow down browsing and JS execution speed. Some more, some less.

If running Speedometer, always do it in Incognito tab with no extensions enabled.

**Comment by piotrnikov** [comment]
@midzer Without any extensions I'm getting 459. 
So more like you :)

**Comment by midzer** [comment]
@piotrnikov But not enough for a M3. With Thorium M119 we had over 600 points on a M3.

Try a fresh reboot and check your background services. Yeah, Safari score is quite impressive.
