### ISSUE TITLE
Spotify webplayer skipping songs

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-MacOS#19]
**System Details**
 - OS: MacOS 14 Sonoma
 - Thorium Version 116.0.5845.169 (Offizieller Build) (arm64)

**Problem**
When opening spotify webplayer and starting a playlist, it will randomly skip songs sometimes one, sometimes 5 or more

**Additional Notes**
Switching back to Chrome, Safari or Firefox this is not happening.

**Comment by gz83** [comment]
It may be caused by the inability to perform widevine VMP verification, please see

https://github.com/Alex313031/Thorium-Win/issues/81#issuecomment-1769072375

@avendretter

**Comment by avendretter** [comment]
uff. thats a bummer. Paying 5k only for having this feature enabled .... oh man 

Thanks for the reply @gz83 :)

**Comment by avendretter** [comment]
uff. thats a bummer. Paying 5k only for having this feature enabled .... oh man

Thanks for the reply @gz83 :) shall we close the ticket then, since it is nothing that can be done here atm?

**Comment by gz83** [comment]
This issue does not need to be closed for the time being, we are still trying to find out if there is a free solution

@avendretter
