### ISSUE TITLE
Add releases to homebrew

### ISSUE THREAD

**Issue by danielneubert** [Alex313031/Thorium-MacOS#24]
### Is your feature request related to a problem? Please describe.
Aside other people I love to install and manage all my software via homebrew. For apps with a gui homebrew has so called casks.

### Describe the solution you'd like, including relevant patches or source
I'd wish a homebrew cask for this browser would exist so you simply could do:
```
brew install thorium-browser --cask
```

### Additional Notes
Not a real note, yet a link to the homebrew software adding process: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by TheDave94** [comment]
There already is cask
`brew install alex313031-thorium`

**Comment by danielneubert** [comment]
@TheDave94 you're right. Don't know why i didn't found it myself in the first hand.

**Comment by Else00** [comment]
Add this to the readme, i had to search on the issues to see if it was available a brew formula.
