### ISSUE TITLE
Thorium is capturing screen!

### ISSUE THREAD

**Issue by Ok9xNirab** [Alex313031/Thorium-MacOS#28]
**System Details**
 - OS: **MacOs Sonoma**
 - Thorium Version: **116.0.5845.169**

With no reason, Thorium is capturing my screen!

**Screenshots**

![Screenshot 2023-10-31 at 10 20 59 PM](https://github.com/Alex313031/Thorium-MacOS/assets/40653908/36c8cb64-66b9-444b-bf8a-85b99a6055ad)

**Comment by gz83** [comment]
Chrome also has this problem, it is recommended to check

https://www.reddit.com/r/MacOS/comments/1570crz/did_anyone_notice_google_chrome_is_capturing_your/

**Comment by j03ll0b0** [comment]
That’s a feature, does Cast ring a bell somewhere?
