### ISSUE TITLE
Extension's popup window not showing up (uBO)

### ISSUE THREAD

**Issue by toooonyy** [Alex313031/Thorium-MacOS#3]
**System Details**
 - OS: macOS 12.6.8
 - Thorium Version 115.0.5790.172 (Official Build) (arm64)
 
**Problem**
ublock's "open the logger" won't open any popup while "open the dashboard" button functions as expected.
Not sure it's unique to macOS or happens on Windows build too.
**Screenshots**
![Kapture 2023-08-27 at 21 02 35](https://github.com/Alex313031/Thorium-MacOS/assets/3480434/85dca329-f8f1-4ff1-9e3d-e05660b2b13a)

**Additional Notes**

Command Line | /Applications/Thorium.app/Contents/MacOS/Thorium --flag-switches-begin --hide-sidepanel-button --show-avatar-button=never --enable-features=ChromeRefresh2023:level/1,Cr2023MacFontSmoothing,HttpsUpgrades,TabHoverCardImages --disable-features=ScrollableTabStrip --flag-switches-end --origin-trial-disabled-features=WebGPU
-- | --

**Comment by gz83** [comment]
Does this happen on 115 version of chromium?

@toooonyy

**Comment by toooonyy** [comment]
@gz83 No, at least not in ungoogle Chromium `115.0.5790.170 (Official Build, ungoogled-chromium) (arm64)`.

**Comment by gz83** [comment]
Please use chromium with the same version number for testing

@toooonyy

**Comment by toooonyy** [comment]
@gz83 

I'm not able to find this particular ver of chromium, do you have any suggestions?

**Comment by gz83** [comment]
https://www.chromium.org/getting-involved/download-chromium/

@toooonyy

**Comment by toooonyy** [comment]
I'm not able to find a version whihc exactly matchs current thorium version.

**Comment by toooonyy** [comment]
Somehow it fixed itself.
