### ISSUE TITLE
Netflix titles are unable to play on Thorium v116.0.5845.169 (arm64) but work fine on Chrome & Brave

### ISSUE THREAD

**Issue by Raj-Joshi-dev** [Alex313031/Thorium-MacOS#30]
**System Details**
 - OS: Mac OS Sonoma 14.1 on Macbook Air M1 
 - Thorium Version v116.0.5845.169

**Problem**
Error Code M7121 - 1331 on Netflix while playing a movie.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-MacOS/assets/52413491/cc44ad5f-29ed-463a-a0f2-99f2df9aa1ea)

**Additional Notes**
Looks like Netflix says the browser is not supported https://help.netflix.com/en/node/61874

What may be the cause of this issue? Thanks.

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-Win/issues/73#issuecomment-1767566078
