### ISSUE TITLE
Not working at all on my configuration

### ISSUE THREAD

**Issue by admiraldaro** [Alex313031/Thorium-MacOS#34]
**System Details**
 - OS: MacOS Ventura 13.6.1 (with OpenCore Legacy)
 - Thorium Version M115.0.5790.172 - 1st Seperate Release and M116.0.5845.169 - 2nd Release
 - Hardware: 
 model: Mac mini Late 2012 (Macmini6,2)
 CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
 GPU: Intel HD Graphics 4000
RAM: 16 GB 1600 MHz DDR3
 
**Problem**
Thorium browser freezes on startup and requires forced task termination.

**Additional Notes**
Forced termination of the task, often fails and you have to do a system reboot.

**Comment by TheKeiki** [comment]
Thorium for MacOS is only compatible with processors with AVX2, so only from Haswell onwards (2013) can run it. We need to wait if Alex can build Thorium with only AVX instructions like in the Windows Branch to be able to use it in old machines with OCLP
