### ISSUE TITLE
When using multiple profiles, the profiles that are not on top stop responding

### ISSUE THREAD

**Issue by alex-munteanu** [Alex313031/Thorium-MacOS#42]
**System Details**
 - OS: MacOS Sonoma 14.3 (same behavior on older 14.2.1)
 - Thorium Version M119.0.6045.214 and M120.0.6099.273

**Problem**
If I have 2 user profiles in Thorium version M119 or later, when I switch between user profiles, pages become unresponsive to scroll or click or any interaction for a few minutes.

i.e.: I have both profile 1 and profile 2 windows open. I am navigating on profile 1 and things work. I switch to profile 2, where I also had some pages open and everything is unresponsive. If I go back to profile 1, things work on profile 1.

If I stay with profile 2 active for enough time (maybe even minutes), it starts working, but then if I switch back to profile 1, things don't work in profile 1.

**Comment by rustedshader** [comment]
OS MacOS Sanoma 14.3
Thorium Version 120.0.6099.273
I am getting same issue if i open an incognito tab above main tab and then switch to main tab it becomes unresponsive and everything on that tab blurs if i move incognito tab  to another desktop window the main tab starts working it didn't happen in 119 it started happening in 120.0.6099.273 ( latest )  . Pls Fix this issue as it is causing so much lag and pretty much un usable at times.

**Comment by achigin** [comment]
Same problem
The workaround im using - open new tab in unresponsive window and search something there in adress bar - then close this tab.

**Comment by Alex313031** [comment]
@alex-munteanu @RustedShader @achigin @insign Fixed in latest M122 release.
