### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by rohshall** [Alex313031/Thorium-MacOS#45]
**System Details**
 - OS: MacOS Sonomo 14.13.1 (M1)
 - Thorium Version M121.0.6167.204
 
**Problem**
The application fails to start. The error is:
`
$ /Applications/Thorium.app/Contents/MacOS/Thorium
[20364:259:0219/215433.033572:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[0219/215433.320930:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
Segmentation fault: 11
`

**Screenshots**
NA
**Additional Notes**
NA

**Comment by megaschatzi** [comment]
Same here ...

**Comment by deebakkarthi** [comment]
Me too

**Comment by midzer** [comment]
Cannot reproduce with manually installed ARM .dmg from https://github.com/Alex313031/Thorium-MacOS/releases/tag/M121.0.6167.204

Had to use https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac though

Did you use the x64 version?

**Comment by vtwinsf** [comment]
Currently, I am using the ARM version without any issues. Moreover, my Mac is equipped with the M1 chip. I'm interested in finding out whether the OP is utilizing the x64 version.

**Comment by rohshall** [comment]
I get the crash on my M1 ARM Mac.

**Comment by deebakkarthi** [comment]
The older version downloaded from github works. But the latest version when installed via homebrew breaks.

**Comment by along02** [comment]
It crashes when I try to add a profile.

**Comment by gz83** [comment]
If the crash is caused by operating the new profile function, it will be fixed in the next version

**Comment by 10zero11** [comment]
I have also found this bug. My install is M1 Arm Mac, installed with homebrew.

It does appear to be caused by the profile selector code.

It can be successfully run as follows from a shell.

   ### open -a "Thorium" --args --profile-directory="Default"

**Comment by bland328** [comment]
> I have also found this bug. My install is M1 Arm Mac, installed with homebrew.
> 
> It does appear to be caused by the profile selector code.
> 
> It can be successfully run as follows from a shell.
> 
> ### open -a "Thorium" --args --profile-directory="Default"

I have the same situation, installed via homebrew, but on an M2 MacBook Air.

After opening Thorium via the `open -a "Thorium" --args --profile-directory="Default"` suggested above, the first attempt to change profiles fails, though subsequent attempts do work.

**Comment by Alex313031** [comment]
@rohshall @10zero11 @bland328 @vtwinsf Sorry guys, stupid mistake on my part. Fixed in latest M122 version.

**Comment by rohshall** [comment]
@Alex313031 thank you so much for fixing this. I tested the M122 version, and it is working beautifully! So, I am closing the issue.

**Comment by 10zero11** [comment]
thank you @Alex313031
