### ISSUE TITLE
Unexpected colored icons in toolbar

### ISSUE THREAD

**Issue by RoyRao2333** [Alex313031/Thorium-MacOS#48]
**System Details**

 - OS: macOS 14.4.1
 - Thorium Version 123.0.6312.133 (Official Build) (arm64)

**Problem**

After upgrading to the latest version of Thorium, some icons such as **Extensions** and **Reload**,  are still colored even set `chrome://flags/#disable-thorium-icons` to `Enabled`.

I need them to be monochrome, thanks!

**Screenshots**

<img width="1573" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/f1c1eb5d-5ded-4ae4-bcbc-fdc4a94a80db">

<img width="383" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/8263062a-ec3d-42e2-ae74-6edd29fd25c1">

Compared to `ungoogled-chromium` 124.0.6367.91 (Official Build, ungoogled-chromium) (arm64):

<img width="351" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/375bddf5-e478-40d6-8a4e-427c17611feb">

**Comment by gz83** [comment]
This is intentional and this is a duplicate issue.

**Comment by RoyRao2333** [comment]
@gz83 

Can you explain why this is intentional and give me a reference of that duplicate issue? Thanks.

**Comment by RoyRao2333** [comment]
Seems like this is the one

https://github.com/Alex313031/thorium/issues/476
