### ISSUE TITLE
Side panel red background

### ISSUE THREAD

**Issue by RoyRao2333** [Alex313031/Thorium-MacOS#49]
**System Details**

 - OS: macOS 14.5
 - Thorium Version 124.0.6367.218 (Official Build) (arm64)

**Screenshots**

<img width="406" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/a23da98d-fec7-4dd8-bb5f-41506006d0bf">

**Additional Notes**

**Comment by k2662** [comment]
> **System Details**
> 
> * OS: macOS 14.5
> * Thorium Version 124.0.6367.218 (Official Build) (arm64)
> 
> **Screenshots**
> 
> <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/31413093/331924082-a23da98d-fec7-4dd8-bb5f-41506006d0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA2MTMsIm5iZiI6MTcxNjE5MDMxMywicGF0aCI6Ii8zMTQxMzA5My8zMzE5MjQwODItYTIzZGE5OGQtZmVjNy00ZGQ4LWJiNWYtNDE1MDYwMDZkMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTAxYjM1YTcxZDRjNmVhNDUxZjYxYTdiM2NhYzMxZWNlYTE1NDBjNTY1YTY5ODQ5M2RjOWQ2NjZkODg1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EjaJlofRl-iMD3Sas_GRcgprWH8Mu-7vppACmLG2k7I">
> **Additional Notes**
> 
> ### And, when will be the next release? I prefer the new UI and I don't wanna launch Thorium through terminal everytime.

am having the same issue here on x86.

**Comment by m4th3r0b0t** [comment]
Same issues for me as well.

**Comment by RoyRao2333** [comment]
<img width="495" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/0a85803b-638a-4872-9abc-be21b41d9b97">

Adding a bookmark

**Comment by lainhathoang** [comment]
Same issues for me as well
![image](https://github.com/Alex313031/Thorium-MacOS/assets/62104936/14b0dbd1-9cd7-43b3-83ee-cd0bf1cdec4a)

**Comment by gokussjx** [comment]
Same issue here, on MacBook Pro M1

**Comment by ChaNg1o1** [comment]
Same.

**Comment by j03ll0b0** [comment]
![Screenshot 2024-07-06 at 6 02 11 PM](https://github.com/Alex313031/Thorium-MacOS/assets/104862685/d1214152-4ce7-482c-9138-beaf724f921c)
Same here

**Comment by BerryStreetBlues** [comment]
> **System Details**
> 
> * OS: macOS 14.5
> * Thorium Version 124.0.6367.218 (Official Build) (arm64)
> 
> **Screenshots**
> 
> <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/31413093/331924082-a23da98d-fec7-4dd8-bb5f-41506006d0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODU0MzUsIm5iZiI6MTcyMDM4NTEzNSwicGF0aCI6Ii8zMTQxMzA5My8zMzE5MjQwODItYTIzZGE5OGQtZmVjNy00ZGQ4LWJiNWYtNDE1MDYwMDZkMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIwNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTdlMjQ0YjJjNjU1YzMzNDMxMTFkZDUwNjA2MGFhNDFjNzVhNmNmYzM4YzhhZTY1YTAxMzUxOGY4Y2VjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqQMzkTDSqBJ8TymIjnCsN1FZ2WyU_78B_LFxRTTO7g">
> **Additional Notes**
> 
> ### And, when will be the next release? I prefer the new UI and I don't wanna launch Thorium through terminal everytime.

@RoyRao2333 you can probably save yourself a bit of a headache by creating a terminal Shortcut.

**Comment by singularitti** [comment]
Same here! Red for Bookmarks and Reading List, and the scrollbar of History and the dropdwon menu in Reading Mode are red!

**Comment by RoyRao2333** [comment]
@Alex313031 @gz83

Hi Folks. Is this fixed in M126? Don't see this is mentioned in the release notes.

This red color is quite unusable. 😭

And since Linux and Win version is released, when will be the macOS version?

**Comment by RoyRao2333** [comment]
Fixed in M126
