### ISSUE TITLE
Bitwarden Biometric Integration

### ISSUE THREAD

**Issue by kladskjasd** [Alex313031/Thorium-MacOS#6]
**System Details**
 - OS: MacOS
 - Thorium Version: 116.0.5845.169 (Official Build) (arm64)

**Problem**
I installed the Bitwarden extension, then tried to set up biometric approval with the Bitwarden Vault. I was asked for a permission, granted it, then tried to activate it. The extension then throws an error mentioning that the browser integration is not set up (see screenshot). 

**Screenshots**
<img width="357" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/96435418/160e7f8d-8f54-402a-a7c6-fffce5edde52">

**Additional Notes**
I am aware this might sound like a Bitwarden issue, but I have the same extension working with biometric approval in the same system with Edge, Chrome, Opera and Brave, so it does seem something specific to Thorium.

**Comment by gz83** [comment]
You may need to correctly set up Thorium's native-messaging-hosts in bitwarden

@kladskjasd

**Comment by Alex313031** [comment]
@kladskjasd Yeah, people have made issues on this before, and someone got it working, just by tweaking the native messaging hosts. Since they don't make these with esoteric or small browsers in mind.

**Comment by henrychea** [comment]
Yup here is the link https://github.com/Alex313031/thorium/issues/363
