### ISSUE TITLE
Thorium Intel future?

### ISSUE THREAD

**Issue by G3JUSTIN** [Alex313031/Thorium-MacOS#61]
**Add all the stuffz here**
This is hands down my favorite browser once I found it, been on it for a while now!, Disappointed to see this new build does not support Intel Macs as there is still a majority out there in use (I myself along with a fair amount of my friends) thank you for all your hard work, Not criticizing that!. Just wondering what the roadmap is for Intel machines? I'm Using the lastest version available for Intel on a 2018 Mac mini and it is far superior to standard Chrome or anything else out there, I know the time is ticking for Intel machines, but with Opencore & MacOS 15 still supporting Intel they got a few years left at minimum, I know these builds Will not work on pre AVX 2 machines, But there is so many 4th Gen+ machines still in use that support AVX 2. Just looking to see if I'm going to have to find another browser and suggest other browsers to my friends on Intel Mac's or if there still is a future ahead?  Again thank you for all the work all of you put into this browser!.

**Comment by RdrSeraphim** [comment]
Also interested in this.

I understand having linking errors for Intel, but is it possible to have these errors posted onto an issue so that maybe there can be some collaboration to try and resolve them?

**Comment by OccamyDMG** [comment]
Also concerned after the latest release dropped support and haven't seen anything since then regarding it being fixed and added back. Thorium is a great browser, but would like to know whether to find an alternative now or not as we're already on an outdated and (within the last 24 hours) broken version.

**Comment by Alex313031** [comment]
@SeraphimRP @OccamyDMG @G3JUSTIN @insign See > https://github.com/Alex313031/Thorium-MacOS/issues/67#issuecomment-2448952447

There is hope lol.
