### ISSUE TITLE
Tabs / Windows Randomly Close

### ISSUE THREAD

**Issue by pixelpicnic** [Alex313031/Thorium-MacOS#63]
**System Details**
 - OS: MacOS Sonoma 14.6.1, M2 Max
 - Thorium Version 126.0.6478.231 (Official Build) (arm64)

**Problem**
Difficult to reproduce!
I've experienced hiccups where multiple tabs on different windows or windows themselves close under certain conditions.

I'm currently trying to rule out extensions, but if anyone has experienced this or knows how to reproduce it, please let me know!

**Comment by Alex313031** [comment]
@pixelpicnic Duplicate. See > https://github.com/Alex313031/Thorium-MacOS/issues/67
