### ISSUE TITLE
Tab Scrolling feels laggy

### ISSUE THREAD

**Issue by RoyRao2333** [Alex313031/Thorium-MacOS#8]
**System Details**
 - OS: macOS Ventura 13.5.2
 - Thorium Version 116.0.5845.169 (Official Build) (arm64)

**Problem**

<img width="435" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/0e995542-4f11-416b-9c7c-67c862822ad0">

I've turned on Thorium Experiments of Tab Scrolling. I don't know when it started, but when I use the Trackpad to scroll tabs horizontally, it may suddenly stuck, and then I need to start scroll again and again. (This problem can be hard to take a screenshot)

It may look like this:

<img width="1800" alt="image" src="https://github.com/Alex313031/Thorium-MacOS/assets/31413093/5ef30a5c-ad02-45a7-a144-e13b05f2178e">

Scrolling may stops abruptly, but you can tell by the black dividing lines on either side that you haven't now reached the first or the last tab.

I didn't notice this before version 116. Maybe this is a new issue in the latest 116 release? **You may need to scroll a little faster to have a better chance of reproducing this issue.** Please take a look and thanks for the efforts! 😊

**Comment by gz83** [comment]
I think you may need to temporarily turn off this feature, which has caused a lot of problems, including many problems recorded in upstream.

At the same time, we will also try to investigate a series of issues caused by this feature, because it has affected many users.

@RoyRao2333

**Comment by RoyRao2333** [comment]
@gz83 

Thanks for the reply!

By the way, do you mean set Tab Scrolling to `Default` or `Disabled`?

**Comment by gz83** [comment]
Please set it to disabled

@RoyRao2333
