### ISSUE TITLE
Certain Pages slow down substantially

### ISSUE THREAD

**Issue by gotschi** [Alex313031/Thorium-MacOS#9]
**System Details**
 - OS: MacOS Sonoma, was already happening in Ventura
 - Thorium Version 116.0.5845.169

**Problem**
Go to a page with many videos, I happen to get surveillance videos on telegram.
So my page is https://web.telegram.org/

-> Page slows every second more until its not navigatable after about 20 seconds. Closing the tab takes a whole time for itself again. 

not useable unfortunately

**Comment by p7r0x7** [comment]
@gotschi do you still experience this on the latest version? It's difficult to reproduce what you describe because of the website you mentioned providing user-exclusive content.

**Comment by gotschi** [comment]
Is fixed, thank you
